USE Ventas_OLTP;
GO


-- 1. CREACIÓN DE TABLAS MAESTRAS
CREATE TABLE DataSources (
    SourceID INT IDENTITY(1,1) PRIMARY KEY,
    SourceType NVARCHAR(50) NOT NULL, -- 'CSV', 'API', 'SQL_EXT'
    LoadDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Customers (
    CustomerID INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(150) NOT NULL,
    LastName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(150),
    Phone NVARCHAR(50),
    City NVARCHAR(50),
    Country NVARCHAR(50)
);

CREATE TABLE Categories (
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    CategoryName NVARCHAR(100) NOT NULL
);

-- 2. CREACIÓN DE PRODUCTOS
CREATE TABLE Products (
    ProductID INT IDENTITY(1,1) PRIMARY KEY,
    ProductName NVARCHAR(150) NOT NULL,
    CategoryID INT CONSTRAINT FK_Products_Categories FOREIGN KEY REFERENCES Categories(CategoryID),
    Price DECIMAL(18,2) NOT NULL,
    Stock INT NOT NULL
);

-- 3. CREACIÓN DE VENTAS (CABECERA)
CREATE TABLE Orders (
    OrderID INT IDENTITY(1,1) PRIMARY KEY,
    OrderDate DATETIME DEFAULT GETDATE() NOT NULL,
    Status NVARCHAR(50),
    CustomerID INT CONSTRAINT FK_Orders_Customers FOREIGN KEY REFERENCES Customers(CustomerID),
    SourceID INT CONSTRAINT FK_Orders_Sources FOREIGN KEY REFERENCES DataSources(SourceID)
);

-- 4. CREACIÓN DE DETALLES (CON CÁLCULO AUTOMÁTICO)
CREATE TABLE OrderDetails (
    OrderDetailID INT IDENTITY(1,1) PRIMARY KEY,
    OrderID INT CONSTRAINT FK_Details_Orders FOREIGN KEY REFERENCES Orders(OrderID) ON DELETE CASCADE,
    ProductID INT CONSTRAINT FK_Details_Products FOREIGN KEY REFERENCES Products(ProductID),
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    LineTotal AS (Quantity * UnitPrice) -- Requisito Práctica 1
);

-- 5.CREACIÓN DE ÍNDICES (PARA RENDIMIENTO DE 100K REGISTROS)
CREATE INDEX IX_Orders_CustomerID ON Orders(CustomerID);
CREATE INDEX IX_Orders_SourceID ON Orders(SourceID);
CREATE INDEX IX_Details_OrderID ON OrderDetails(OrderID);
CREATE INDEX IX_Details_ProductID ON OrderDetails(ProductID);
GO



